name: "aws-terraform-eks"

on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  terraform:
    name: Terraform
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: "Terraform Init"
        run: terraform init

      - name: Terraform Apply
        run:  terraform apply --auto-approve
    
